# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:  
  push:
  pull_request:
  
jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v1     
        with:
          fetch-depth: 1
          
          
      - name: Validate the Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1 
      
      - name: Test
        run: |
          chmod +x run.sh
          NO_INTERRACTIVE=1 ./run.sh tests-lwjgl3:test -i

      - name: Upload lwjgl3 reports
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: reports-lwjgl3
          path: tests-lwjgl3/build/reports
          
